"""Exact geodesic computations using geometry-central."""

from __future__ import annotations

import numpy

__all__: list[str] = ["GeodesicMesh"]

class GeodesicMesh:
    def __init__(self, V: numpy.ndarray, F: numpy.ndarray) -> None: ...
    def distance_from_vertices(self, sources: list[int]) -> numpy.ndarray: ...
    def edge_vertex_indices(self) -> numpy.ndarray: ...
    def face_vertex_indices(self) -> numpy.ndarray: ...
    def n_edges(self) -> int: ...
    def n_faces(self) -> int: ...
    def n_vertices(self) -> int: ...
    def trace_path(
        self, source: int, target: int
    ) -> list[tuple[int, int, numpy.ndarray]]: ...
    def vertex_positions(self) -> numpy.ndarray: ...
