"""Exact geodesic computations using geometry-central."""

from __future__ import annotations

import numpy

__all__: list[str] = ["GeodesicMesh", "SurfacePoint"]

class SurfacePoint:
    type: int
    index: int
    coords: numpy.ndarray

class GeodesicMesh:
    def __init__(self, V: numpy.ndarray, F: numpy.ndarray) -> None: ...
    def distance_from_vertices(self, sources: list[int]) -> numpy.ndarray: ...
    def edge_vertex_indices(self) -> numpy.ndarray: ...
    def face_vertex_indices(self) -> numpy.ndarray: ...
    def make_edge_point(self, edge: int, t: float) -> SurfacePoint: ...
    def make_face_point(
        self, face: int, b0: float, b1: float, b2: float
    ) -> SurfacePoint: ...
    def make_vertex_point(self, vertex: int) -> SurfacePoint: ...
    def n_edges(self) -> int: ...
    def n_faces(self) -> int: ...
    def n_vertices(self) -> int: ...
    def trace_path(
        self, source: int, target: int
    ) -> list[tuple[int, int, numpy.ndarray]]: ...
    def trace_path_points(
        self, source: SurfacePoint, target: SurfacePoint
    ) -> list[SurfacePoint]: ...
    def vertex_positions(self) -> numpy.ndarray: ...
